# Example configuration for training/validation with Roboflow or CVAT + Ultralytics
dataset:
  source: cvat   # options: roboflow | cvat

cvat:
  # Provide either a path to a CVAT export zip, or a root directory of an extracted export.
  zip_path: ./data/project_2_dataset_2025_08_08_13_38_51_ultralytics yolo detection 1.0.zip           # e.g., ./exports/my_cvat_export.zip
  root: null               # e.g., ./data/my-cvat-dataset
  location: ./data         # where to extract if zip_path is provided
  format: null             # optional: yolo | coco (auto-detected if null)
  data_yaml: null          # optional explicit data.yaml path
  names: null              # optional class name list when not present in export

model:
  backend: ultralytics       # only 'ultralytics' supported for now
  arch: yolov8n.pt           # model name or path to checkpoint
  imgsz: 640
  lr: 0.001
  epochs: 20
  batch: 16
  device: null               # e.g. "cuda:0" or [0,1]
  seed: 42

train:
  project_dir: runs/train
  name: exp
  resume: false

val:
  project_dir: runs/val
  name: exp
