# Example configuration for training/validation with Roboflow or CVAT + Ultralytics
dataset:
  source: roboflow   # options: roboflow | cvat
roboflow:
  # api_key: null            # optional; will read from ROBOFLOW_API_KEY if null
  workspace: your-workspace
  project: your-project
  version: 1
  split: yolov8              # export format; 'yolov8' recommended
  format: null               # override export format if needed
  location: ./data           # where to store dataset
  # data_yaml: ./data/your-dataset/data.yaml  # optional explicit path if auto-detection fails

cvat:
  # Provide either a path to a CVAT export zip, or a root directory of an extracted export.
  zip_path: null           # e.g., ./exports/my_cvat_export.zip
  root: null               # e.g., ./data/my-cvat-dataset
  location: ./data         # where to extract if zip_path is provided
  format: null             # optional: yolo | coco (auto-detected if null)
  data_yaml: null          # optional explicit data.yaml path
  names: null              # optional class name list when not present in export

model:
  backend: ultralytics       # ultralytics | transformers
  arch: yolov8n.pt           # yolov8n.pt or SenseTime/deformable-detr-with-box-refine when backend=transformers
  imgsz: 640
  lr: 0.001
  epochs: 50
  batch: 16
  device: null               # e.g. "cuda:0" or [0,1]
  seed: 42

train:
  project_dir: runs/train
  name: exp
  resume: false

val:
  project_dir: runs/val
  name: exp
