# Example configuration for training/validation with Roboflow or CVAT + Ultralytics
dataset:
  source: roboflow   # options: roboflow | cvat
roboflow:
  # api_key: null            # optional; will read from ROBOFLOW_API_KEY if null
  workspace: your-workspace
  project: your-project
  version: 1
  split: yolov8              # export format; 'yolov8' recommended
  format: null               # override export format if needed
  location: ./data           # where to store dataset
  # data_yaml: ./data/your-dataset/data.yaml  # optional explicit path if auto-detection fails

cvat:
  # Provide either a path to a CVAT export zip, or a root directory of an extracted export.
  zip_path: null           # e.g., ./exports/my_cvat_export.zip
  root: null               # e.g., ./data/my-cvat-dataset
  location: ./data         # where to extract if zip_path is provided
  format: null             # optional: yolo | coco (auto-detected if null)
  data_yaml: null          # optional explicit data.yaml path
  names: null              # optional class name list when not present in export

model:
  backend: ultralytics       # ultralytics | transformers
  arch: yolov8n.pt           # yolov8n.pt or SenseTime/deformable-detr-with-box-refine when backend=transformers
  imgsz: 640
  lr: 0.001
  epochs: 50
  batch: 16
  device: null               # e.g. "cuda:0" or [0,1]
  seed: 42

train:
  project_dir: runs/train
  name: exp
  resume: false

val:
  project_dir: runs/val
  name: exp

augmentation:
  enable: true
  # Settings for Ultralytics backend (forwarded directly). Uncomment / edit as needed.
  # ultralytics:
  #   mosaic: 0.5
  #   mixup: 0.1
  #   hsv_h: 0.015
  #   hsv_s: 0.7
  #   hsv_v: 0.4
  # Basic generic knobs (used by transformers backend via Albumentations pipeline)
  hflip: 0.5
  brightness: 0.2
  contrast: 0.2
  hue: 0.02
  saturation: 0.2
  scale_min: 0.9
  scale_max: 1.1
  rotate: 0      # set >0 to enable random rotation
  blur: 0.0
  cutout: 0
