# Example configuration for training/validation with Roboflow + Ultralytics
roboflow:
  # api_key: null            # optional; will read from ROBOFLOW_API_KEY if null
  workspace: test-0dgvp
  project: rust-rt3ec
  version: 2
  split: yolov8              # export format; 'yolov8' recommended
  format: null               # override export format if needed
  location: ./data/rust.v2i.yolov8           # where to store dataset
  # data_yaml: ./data/data.yaml

model:
  backend: ultralytics       # only 'ultralytics' supported for now
  arch: yolov8n.pt           # model name or path to checkpoint
  imgsz: 640
  lr: 0.00005
  epochs: 20
  batch: 16
  device: null               # e.g. "cuda:0" or [0,1]
  seed: 42

train:
  project_dir: runs/train
  name: expyolo
  resume: false

val:
  project_dir: runs/val
  name: expyolo
